# Header
menu:
  Home: /
  CV: /cv/
  Old Articles: /articles/
  Archives: /archives/
  About: /about/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-11887495-2
google_verification: buCvLjWPMm27OW9w9-QcwTZZdPtT9B3R190Z1Fmjins
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
